// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8bo5hUAVwp5XvLjqMZfzDwBVtExD8GNI',
    appId: '1:1052203225112:web:3f107ecdc1c3f0d525b36d',
    messagingSenderId: '1052203225112',
    projectId: 'life-plus-c3b6c',
    authDomain: 'life-plus-c3b6c.firebaseapp.com',
    storageBucket: 'life-plus-c3b6c.firebasestorage.app',
    measurementId: 'G-HRESK30H5V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ2G3nmoRGyCj2PMz1PBzcdnSscJlUvhI',
    appId: '1:1052203225112:android:ce3b2d51d75caa7525b36d',
    messagingSenderId: '1052203225112',
    projectId: 'life-plus-c3b6c',
    storageBucket: 'life-plus-c3b6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs4kFbiATBYVQLy0Tc7gIgn0cG66bgubo',
    appId: '1:1052203225112:ios:7d923ec4a39070cb25b36d',
    messagingSenderId: '1052203225112',
    projectId: 'life-plus-c3b6c',
    storageBucket: 'life-plus-c3b6c.firebasestorage.app',
    iosBundleId: 'com.example.adminUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs4kFbiATBYVQLy0Tc7gIgn0cG66bgubo',
    appId: '1:1052203225112:ios:7d923ec4a39070cb25b36d',
    messagingSenderId: '1052203225112',
    projectId: 'life-plus-c3b6c',
    storageBucket: 'life-plus-c3b6c.firebasestorage.app',
    iosBundleId: 'com.example.adminUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8bo5hUAVwp5XvLjqMZfzDwBVtExD8GNI',
    appId: '1:1052203225112:web:0934c2b33b7da26225b36d',
    messagingSenderId: '1052203225112',
    projectId: 'life-plus-c3b6c',
    authDomain: 'life-plus-c3b6c.firebaseapp.com',
    storageBucket: 'life-plus-c3b6c.firebasestorage.app',
    measurementId: 'G-C5VFV93JQF',
  );
}
