// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc0DD9ZCKouX_Agg6HnEfuwRHqD0JfKIo',
    appId: '1:40735780102:web:db7a3bbd89f5eb00ca8287',
    messagingSenderId: '40735780102',
    projectId: 'life-plus-app-9f1d6',
    authDomain: 'life-plus-app-9f1d6.firebaseapp.com',
    storageBucket: 'life-plus-app-9f1d6.firebasestorage.app',
    measurementId: 'G-QJGEF43GE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWQ_VZm1BVkZxSnszL25O8sv9Nnd9YIAI',
    appId: '1:40735780102:android:47c7997c82c93839ca8287',
    messagingSenderId: '40735780102',
    projectId: 'life-plus-app-9f1d6',
    storageBucket: 'life-plus-app-9f1d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWj81-qku5JZpwYSaaKeSf7u7FKjyxhVw',
    appId: '1:40735780102:ios:6392ac6e629273b7ca8287',
    messagingSenderId: '40735780102',
    projectId: 'life-plus-app-9f1d6',
    storageBucket: 'life-plus-app-9f1d6.firebasestorage.app',
    iosBundleId: 'com.example.patientUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWj81-qku5JZpwYSaaKeSf7u7FKjyxhVw',
    appId: '1:40735780102:ios:6392ac6e629273b7ca8287',
    messagingSenderId: '40735780102',
    projectId: 'life-plus-app-9f1d6',
    storageBucket: 'life-plus-app-9f1d6.firebasestorage.app',
    iosBundleId: 'com.example.patientUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBc0DD9ZCKouX_Agg6HnEfuwRHqD0JfKIo',
    appId: '1:40735780102:web:3e03e2ff395f913fca8287',
    messagingSenderId: '40735780102',
    projectId: 'life-plus-app-9f1d6',
    authDomain: 'life-plus-app-9f1d6.firebaseapp.com',
    storageBucket: 'life-plus-app-9f1d6.firebasestorage.app',
    measurementId: 'G-Z640QNZ2BX',
  );
}
